# Crystal Quest Environment

- modeled off of https://github.com/openai/gym/blob/master/gym/envs/box2d/lunar_lander.py and
https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py
- will put in external file when done

In [32]:
import sys
sys.path.append('../crystal_quest/')
import crystal_quest_env as cq
import imp 
imp.reload(cq) # reload after making changes

<module 'crystal_quest_env' from '../crystal_quest/crystal_quest_env.py'>

In [33]:
env = cq.Wave1Env()

In [34]:
obs = env.reset()
env.ship_location

array([19, 12])

# Crystal Quest Rendering Environment (Simplest)

In [35]:
# randomly sampling actions and visualizing 
env = cq.Wave1Env()
obs = env.reset()

In [36]:
obs.shape

(39, 25, 4)

In [37]:
# randomly sampling actions and visualizing 
env = cq.Wave1Env()
obs = env.reset()
for i in range(500):
    obs,r,done = env.step(env.action_space.sample())
    env.render()
env.render(close=True)

[ 24.  24.]
<class 'numpy.ndarray'>


IndexError: arrays used as indices must be of integer (or boolean) type

# Scratch

In [69]:
feature_vect

array([ 0.66666667,  0.33333333])

In [70]:
feature_vect_prev

array([ 0.68085106,  0.31914894])

In [71]:
[agent.calculateQval(feature_vect,a) for a in range(5)]

[17.704599435101848,
 17.774774697559227,
 17.519522482412349,
 0.97630795760063571,
 17.489401480689274]

In [85]:
feature_vect

array([ 0.66666667,  0.33333333])

In [86]:
qval_tp1_best = np.max([agent.calculateQval(feature_vect,a) for a in range(5)])
qval_tp1_best

17.774774697559227

In [88]:
feature_vect_prev

array([ 0.68085106,  0.31914894])

In [84]:
qval_tp = agent.calculateQval(feature_vect_prev,action)
qval_tp

17.702304355251506

In [76]:

# calculate td
td = (0 + agent.gamma*qval_tp1_best) - qval_tp
td

-0.10527740466786994

In [77]:
td

-0.10527740466786994

In [78]:
feature_vect_prev

array([ 0.68085106,  0.31914894])

In [79]:
agent.alpha

0.1

In [80]:
agent.alpha*td*feature_vect_prev

array([-0.00716782, -0.00335992])

In [1390]:

# update theta  
self.thetas[:,action]+= self.alpha*td*feature_vect_t
self.thetas[:,action]=self.thetas[:,action]/np.sum(np.abs(self.thetas[:,action]))


NameError: name 'self' is not defined

In [136]:
import argparse
import gym
from gym import wrappers
import os.path as osp
import random
import numpy as np
import tensorflow as tf
import tensorflow.contrib.layers as layers

In [137]:
def get_env(task, seed):
    env_id = task.env_id

    env = gym.make(env_id)

    set_global_seeds(seed)
    env.seed(seed)

    expt_dir = '/tmp/hw3_vid_dir2/'
    env = wrappers.Monitor(env, osp.join(expt_dir, "gym"), force=True)
    env = wrap_deepmind(env)

    return env

In [138]:
def set_global_seeds(i):
    try:
        import tensorflow as tf
    except ImportError:
        pass
    else:
        tf.set_random_seed(i)
    np.random.seed(i)
    random.seed(i)